### PR TITLE
Add a language definition

### PR DESCRIPTION
**Pull request by TheComputerGuy96**
This should work around https://github.com/mesonbuild/meson/issues/13651

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
This shouldn't be necessary. I was able to successfully package for both Fedora and openSUSE without this. What are you doing that seems to trip up over it?

**Comment by TheComputerGuy96** [comment]
> This shouldn't be necessary. I was able to successfully package for both Fedora and openSUSE without this. What are you doing that seems to trip up over it?

I was testing a dirty build of this project and the issue above occurred 🐸

**Comment by misyltoad** [comment]
Do you get the same issue building `wayland-protocols`?

**Comment by TheComputerGuy96** [comment]
> Do you get the same issue building `wayland-protocols`?

Of course not (because of a lucky coincidence in `tests/meson.build`)

**Comment by serebit** [comment]
> > Do you get the same issue building `wayland-protocols`?
> 
> Of course not (because of a lucky coincidence in `tests/meson.build`)

What's the coincidence?

**Comment by TheComputerGuy96** [comment]
> What's the coincidence?

I mean it's this: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/60c6b510979a48fc3ff62237e4fc33b5adef193e/tests/meson.build#L24

**Comment by misyltoad** [comment]
Makes sense then.

**Pull request merged**
